name: Build and test
on:
  pull_request:
    branches:
      - master

jobs:
  build-test:
    name: Build and test
    strategy:
      matrix:
        include:
          - os: windows-latest
          - os: macos-latest
          - os: ubuntu-latest
    
    uses: HavenDV/workflows/.github/workflows/dotnet_build-test-publish.yml@main
    with:
      os: ${{ matrix.os }}
      generate-build-number: false
      conventional-commits-publish-conditions: false
      enable-caching: false
      additional-test-arguments: '--logger GitHubActions'